name: Verify

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

  workflow_dispatch:

  schedule:
    # every First Saturday of the month at 00:00 UTC
    - cron: "0 0 1-7 * 6"

permissions:
  pull-requests: write # This action modifies PRs
  contents: write # This action adds commits to PRs

jobs:

  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      # Free GitHub Actions Environment Disk Space

      - uses: actions/checkout@v4
      - name: Run Plugin Verification tasks
        run: ./gradlew 

